version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cluster/pulumi"
    schedule:
      interval: "daily"
    assignees:
      - "krzysztofczyz-da"
      - "mblaze-da"
      - "martinflorian-da"
    labels:
      - "static"
    commit-message:
      prefix: "[ci] "
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    # minor and patch version upgrades get pulled into a single PR
    # major versions create PRs one by one (for easier resolution)
    groups: 
      production-dependencies:
        IDENTIFIER: "pulumi-production-dependencies"
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        IDENTIFIER: "pulumi-development-dependencies"
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/load-tester"
    schedule:
      interval: "daily"
    assignees:
      - "krzysztofczyz-da"
      - "mblaze-da"
      - "martinflorian-da"
    labels:
      - "static"
    commit-message:
      prefix: "[ci] "
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    # minor and patch version upgrades get pulled into a single PR
    # major versions create PRs one by one (for easier resolution)
    groups:
      production-dependencies:
        IDENTIFIER: "load-tester-production-dependencies"
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        IDENTIFIER: "load-tester-development-dependencies"
        dependency-type: "development"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/" # For GitHub Actions '/' means .github/workflows/**/*.{yaml,yml}
    # Check for updates to GitHub Actions every week
    schedule:
      interval: "weekly"
    labels:
      - "static"
    assignees:
      - "krzysztofczyz-da"
      - "mblaze-da"
      - "martinflorian-da"
    commit-message:
      prefix: "[ci] "