# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "ghcr.io/digital-asset/decentralized-canton-sync/docker"
resources:
  limits:
    memory: 12Gi
  requests:
    cpu: "0.5"
    memory: 1Gi

# Custom annotations and labels for deployed resources
pod:
  annotations: {}
  labels: {}

db:
  volumeSize: 2800Gi
  volumeStorageClass: standard-rwo
  pvcTemplateName: pg-data
  maxConnections: 300
  maxWalSize: 2GB

# Extra PostgreSQL command-line arguments (optional)
# extraArgs:
#   - "-c"
#   - "shared_buffers=256MB"
#   - "-c"
#   - "wal_buffers=-1"

persistence:
  secretName: "postgres-secrets"
# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:

