# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefix" (list .Values "config-cometbft") }}
  namespace: {{ .Release.Namespace }}
data:
  config.toml: {{ include "configToml" $ | trim | quote }}
  genesis.json: {{ include "genesisJson" $ | trim | quote }}
