# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefix" (list .Values "initial-data") }}
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "setup/shared/initial-data/*").AsConfig | indent 2 }}
