# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
{{ if not .Values.node.keysSecret  }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "prefix" (list .Values "cometbft-keys") }}
data:
  node_key.json: {{ include "nodeKeyJson" .Values.node.privateKey | trim |  b64enc }}
  priv_validator_key.json: {{ include "privValidatorKeyJson" . | trim | b64enc }}
{{ end }}
