# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{ $_ := required ".Release.Namespace is required." .Release.Namespace }}

{{ $_ := required ".Values.imageRepo is required." .Values.imageRepo }}

{{ $_ := required ".Values.defaultJvmOptions is required." .Values.defaultJvmOptions }}

{{ $_ := required ".Values.scanAddress is required." .Values.scanAddress }}
