# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: splitwell-app-ingress
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "splitwell.{{ (.Values.cluster).hostname }}"
  gateways:
  - cluster-ingress/cn-http-gateway
  http:
  - match:
    - port: 443
    route:
    - destination:
        port:
          number: 5213
        host: splitwell-app.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: splitwell-domain-ingress
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "{{ (.Values.cluster).hostname }}"
  gateways:
  - cluster-ingress/cn-apps-gateway
  http:
  - match:
    - port: 5108
    route:
    - destination:
        port:
          number: 5008
        host: domain.{{ .Release.Namespace }}.svc.cluster.local
