# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: splice-info
version: VERSION_NUMBER
appVersion: VERSION_NUMBER

description: "A simple web server that serves JSON files with deployment and runtime information."
