approvedSvIdentities:
  - name: Digital-Asset-2
    publicKey: PUBKEY_0==
    rewardWeightBps: 100000
  - name: SV1
    publicKey: PUBLIC_KEY_1==
    rewardWeightBps: 1000000
  - name: SV2
    publicKey: PUBLIC_KEY_2==
    rewardWeightBps: 150000
    extraBeneficiaries:
      - beneficiary: "mock-validator-1::123456789012345678901234567890123456789012234567890123456789012345678"
        weight: 100000
      - beneficiary: "Broadridge-validator-1::1220c89a73e7b47f16dfb48a521eeedfe2a8620ea1b19b815ab427388d9f5427faa5"
        weight: 50000
  - name: Digital-Asset-1
    publicKey: THIS_IS_THE_WRONG_KEY
    # this is the right reward weight though
    rewardWeightBps: 150000
