# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: splice-validator
type: application
version: VERSION_NUMBER
appVersion: VERSION_NUMBER

description: Global Synchronizer Validator

dependencies:
- name: splice-util-lib
  version: 0.3.0
  repository: file://../splice-util-lib
