# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{ $_ := required ".Release.Namespace is required." .Release.Namespace }}

{{ $_ := required ".Values.cluster.hostname is required." (.Values.cluster).hostname }}
{{ $_ := required ".Values.cluster.svNamespace is required." (.Values.cluster).svNamespace }}
#  if ingress.splitwell is set to true then require the active migration id
{{- if .Values.ingress.splitwell }}
{{ $_ := required ".Values.ingress.decentralizedSynchronizer.activeMigrationId is required." ((.Values.ingress).decentralizedSynchronizer).activeMigrationId }}
{{- end }}
