# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "ghcr.io/digital-asset/decentralized-canton-sync/docker"

# -- Annotations and labels for the participant pod
pod:
  annotations: {}
  labels: {}

defaultJvmOptions: -XX:+UseG1GC -XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=70 -Dscala.concurrent.context.numThreads=8 -XX:ActiveProcessorCount=8 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/persistent-data
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: "2"
    memory: 2Gi

metrics:
  enable: false
  release: prometheus-grafana-monitoring
  interval: 30s

persistence:
  databaseName: cantonnet_scan
  schema: scan
  host: postgres
  port: 5432
  user: cnadmin
  secretName: "postgres-secrets"

migration:
  id: 0

failOnAppVersionMismatch: true

spliceInstanceNames:
  networkName: # Please provide a value as provided in the docs
  networkFaviconUrl: # Please provide a value as provided in the docs
  amuletName: # Please provide a value as provided in the docs
  amuletNameAcronym: # Please provide a value as provided in the docs
  nameServiceName: # Please provide a value as provided in the docs
  nameServiceNameAcronym: # Please provide a value as provided in the docs

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:

# set the poll interval used by the UI in milliseconds (optional)
# uiPollInterval:

service:
  ui:
    port: 80
