# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- $appIdentifier :=  "sv-app" }}
{{- if .Values.metrics.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Values.metrics.release }}
    migration: {{ .Values.migration.id | quote }}
  name: {{ $appIdentifier }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:

    - port: metrics
      interval: {{ .Values.metrics.interval }}

  selector:
    matchLabels:
      app: {{ $appIdentifier }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  targetLabels:
    - migration

{{- end }}
