# Replace MIGRATION_ID with the current migration ID of the global synchronizer.
migration:
  id: "MIGRATION_ID"

# Replace MIGRATION_ID with the current migration ID of the global synchronizer.
participantAddress: "participant-MIGRATION_ID"
sequencerAddress: "global-domain-MIGRATION_ID-sequencer"
mediatorAddress: "global-domain-MIGRATION_ID-mediator"

persistence:
  host: apps-pg
  secretName: apps-pg-secret

spliceInstanceNames:
  networkName: # Please provide a value as provided in the docs
  networkFaviconUrl: # Please provide a value as provided in the docs
  amuletName: # Please provide a value as provided in the docs
  amuletNameAcronym: # Please provide a value as provided in the docs
  nameServiceName: # Please provide a value as provided in the docs
  nameServiceNameAcronym: # Please provide a value as provided in the docs
