# Replace MIGRATION_ID with the current migration ID of the global synchronizer.
migration:
  id: "MIGRATION_ID"

# replace MIGRATION_ID with the current migration ID of the global synchronizer
participantAddress: "participant-MIGRATION_ID"

# Replace YOUR_SV_NAME with the name you provided for your SV identity
nodeIdentifier: YOUR_SV_NAME

svValidator: true

persistence:
  host: apps-pg
  secretName: apps-pg-secret

topup:
  enabled: false

scanClient:
  scanType: "trust-single"
  scanAddress: "TRUSTED_SCAN_URL"
