# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{ $_ := required ".Release.Namespace is required." .Release.Namespace }}
{{ $_ := required ".Values.cluster.cantonHostname is required." (.Values.cluster).cantonHostname }}
{{ $_ := required ".Values.cluster.daHostname is required." (.Values.cluster).daHostname }}

