# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "ghcr.io/digital-asset/decentralized-canton-sync/docker"
withSvIngress: true
ingress:
  wallet: true
  sv: true
  ans: true
  scan: true
  sequencer: true
  splitwell: false
  decentralizedSynchronizer:
    migrationIds: ["0"]
spliceDomainNames:
  nameServiceDomain: "ans"
rateLimit:
  scan:
    enable: false
    acs:
      limit: 10

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:
