# Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: splice-util-lib
type: library
version: 0.3.0
appVersion: 0.3.0

description: Splice Deployment Utilities
