name: Auto-assign issues from external contributors

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-24.04
    steps:
      - name: Assign issue from external contributors
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const issue = context.payload.issue;
            const author = issue.user.login.toLowerCase();
            const isInternalContributor = author.endsWith('-da') || author === 'cocreature';
            if (issue.assignees.length === 0 && !isInternalContributor) {
              console.log('Assigning issue to the triage team...');
              await github.rest.issues.addAssignees({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: ['isegall-da', 'martinflorian-da', 'ray-roestenburg-da', 'rautenrieth-da'],
              });
            }
