name: Remind to backport PRs to release branches
on:
  pull_request:
    types: [opened, reopened]
    paths:
      - cluster/deployment/devnet/**
      - cluster/deployment/testnet/**
      - cluster/deployment/mainnet/**
      - '**/expected-devnet.json'
      - '**/expected-testnet.json'
      - '**/expected-mainnet.json'
    # TODO(DACH-NY/canton-network-node#16006): other cases to consider:
    # - All commits on a release-line branch

jobs:
  add_comment:
    runs-on: self-hosted-docker-tiny
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js (in order to install npm packages)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm install js-yaml
      - name: Main script
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          retries: 3
          script: |
            const jsyaml = require('js-yaml')
            const script = require('.github/actions/scripts/backport_reminder.js')
            await script({github, context, jsyaml})
