name: Docs
on:
  workflow_call:
    inputs:
      commit_sha:
        type: string
        required: false
        default: ""

jobs:
  docs:
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12

    steps:

      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Setup
        id: setup
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: static_tests
          save_nix_cache: true
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build docs
        uses: ./.github/actions/sbt/execute_sbt_command
        with:
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          # We Test/compile here as the docs job is the one that pushes to the SBT cache
          # as it finishes fastest and we want to ensure that it includes test sources.
          cmd: "Test/compile docs/bundle"

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@2d163be3ddce01512f3eea7ac5b7023b5d643ce1
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push' #FIXME: uncomment
        with:
          path: docs/html/html

      # TODO(#1028): Reenable this
      # - name: Push documentation
      #   uses: ./.github/actions/nix/run_bash_command_in_nix
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   env:
      #     GH_USER: ${{ github.actor }}
      #     GH_TOKEN: ${{ secrets.GH_ISSUES }}
      #   with:
      #     additional_nix_args: "--keep GH_USER --keep GH_TOKEN"
      #     cmd: |
      #       REPO_DIR="$(mktemp -d)"
      #       export GIT_SSH_COMMAND="/usr/bin/ssh"
      #       git config --global user.email "splice-maintainers@digitalasset.com"
      #       git config --global user.name "DA Automation"
      #       git clone https://$GH_USER:$GH_TOKEN@github.com/digital-asset/decentralized-canton-sync.git "$REPO_DIR" -b docs
      #       # Given that we just wanna overwrite anything an rm + cp seems more straightforward than an rsync.
      #       rm -rf "$REPO_DIR/docs"
      #       cp -r "docs/html/html" "$REPO_DIR/docs"
      #       # Required to make GH service the _static directory properly.
      #       touch "$REPO_DIR/docs/.nojekyll"
      #       cd "$REPO_DIR"
      #       git add .
      #       git commit -m 'Update documentation'
      #       git push origin docs

      - name: Post-SBT job
        uses: ./.github/actions/sbt/post_sbt
        with:
          cache_version: 4
          setup_sbt_cache_hits: ${{ steps.setup.outputs.sbt_cache_hits }}

      - name: Report Failures on Slack & Github
        if: failure() && github.event_name == 'push'
        uses: ./.github/actions/tests/failure_notifications
        with:
          workload_identity_provider: '${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_SA }}'
          notifications_url: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_URL }}'
          slack_channel: '${{ secrets.FAILURE_NOTIFICATIONS_SLACK_CHANNEL }}'

  publish_docs:
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main' #FIXME:  uncomment
    needs: docs
    runs-on: self-hosted-docker-tiny

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@854d7aa1b99e4509c4d1b53d69b7ba4eaf39215a
