name: Docs
on:
  workflow_call:
    inputs:
      commit_sha:
        type: string
        required: true

jobs:
  docs:
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12

    steps:

      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Setup
        id: setup
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: docs
          save_nix_cache: true
          save_nix_cache_to_gcp: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          oss_only: true
          upload_workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER_SPLICE }}
          upload_service_account: ${{ secrets.CACHE_UPLOADER_SA }}

      - name: Build docs
        uses: ./.github/actions/sbt/execute_sbt_command
        with:
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          # We Test/compile here as the docs job is the one that pushes to the SBT cache
          # as it finishes fastest and we want to ensure that it includes test sources.
          cmd: "Test/compile docs/bundle"

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@2d163be3ddce01512f3eea7ac5b7023b5d643ce1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          path: docs/html/html

      - name: Post-SBT job
        uses: ./.github/actions/sbt/post_sbt
        with:
          cache_version: 6
          setup_sbt_cache_hits: ${{ steps.setup.outputs.sbt_cache_hits }}

      - name: Report Failures on Slack & Github
        if: failure() && (github.event_name == 'push' || github.event_name == 'schedule')
        uses: ./.github/actions/tests/failure_notifications
        with:
          workload_identity_provider: '${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_SA }}'
          notifications_url: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_URL }}'
          slack_channel: '${{ secrets.FAILURE_NOTIFICATIONS_SLACK_CHANNEL }}'
