name: UI tests
on: workflow_call

jobs:
  ui_tests:
    runs-on: self-hosted-k8s-small
    container:
      image: ghcr.io/digital-asset/decentralized-canton-sync/docker/splice-test-ci:0.3.12

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Skip on [static]
        id: skip
        shell: bash
        run: |
          last_commit_msg=$(git log -1 --pretty=%B)
          echo "Last commit message: $last_commit_msg"
          if [[ "${{ github.event_name }}" == 'pull_request' ]] && [[ "$last_commit_msg" == *"[static]"* ]]; then
            echo "Skipping UI tests because of [static] label"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup
        id: setup
        if: steps.skip.outputs.skip != 'true'
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: ui_tests
          artifactory_user: ${{ vars.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Run UI tests
        if: steps.skip.outputs.skip != 'true'
        uses: ./.github/actions/sbt/execute_sbt_command
        with:
          cmd: "apps-common-frontend/npmTest"
          fail_on_error_in_output: false

      - name: Generate report
        uses: ./.github/actions/sbt/execute_sbt_command
        if: failure()
        with:
          cmd: "apps-common-frontend/npmGenerateViteReport"
          fail_on_error_in_output: false

      - name: Post-SBT job
        if: steps.skip.outputs.skip != 'true'
        uses: ./.github/actions/sbt/post_sbt
        with:
          cache_version: 1
          setup_sbt_cache_hits: ${{ steps.setup.outputs.sbt_cache_hits }}

      - name: Upload logs
        # We upload the logs on not success so that we also capture them for cancelled runs
        # Unfortunately when our apps don't init and stop with sys.exit(1) the run is considered cancelled (as it fails with a timeout) but we do need the logs
        if: ${{ !success() }}
        uses: ./.github/actions/sbt/upload_logs
        with:
          name: "vite-report"

      - name: Report Failures on Slack & Github
        if: failure() && github.event_name == 'push'
        shell: bash
        env:
          SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_ISSUES }}
        run: ./.circleci/notification-scripts/failure_notification.py
