name: TS CLI Tests
on:
  workflow_call:
    inputs:
      commit_sha:
        type: string
        required: true

jobs:
  ts_cli_tests:
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12

    steps:

      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Checkout the PR head commit to get the commit message first
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check if static only
        uses: ./.github/actions/tests/skip_on_static
        id: skip
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out repository code
        uses: actions/checkout@v4
        if: inputs.commit_sha != ''
        with:
          ref: ${{ inputs.commit_sha }}

      - name: Setup
        id: setup
        if: steps.skip.outputs.skip != 'true'
        uses: ./.github/actions/tests/common_test_setup
        with:
          test_name: ts_cli
          target: 'oss'

      - name: Run Token Standard CLI tests
        if: steps.skip.outputs.skip != 'true'
        uses: ./.github/actions/sbt/execute_sbt_command
        with:
          cmd: "token-standard-cli/npmTest"
          fail_on_error_in_output: true


      - name: Report Failures on Slack & Github
        if: failure() && (github.event_name == 'push' || github.event_name == 'schedule')
        uses: ./.github/actions/tests/failure_notifications
        with:
          workload_identity_provider: '${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_SA }}'
          notifications_url: '${{ secrets.FAILURE_NOTIFICATIONS_INVOKER_URL }}'
          slack_channel: '${{ secrets.FAILURE_NOTIFICATIONS_SLACK_CHANNEL }}'
