name: CI on PRs (Splice Contributors)
on: # TODO: replace with main only, once a day
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-perftest
  cancel-in-progress: true

permissions:
  id-token: write # Required for GCP Workload Identity for failure notifications
  contents: read

jobs:
  performance_tests:
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12
    name: Performance Tests
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - name: Connection check
        shell: bash
        run: |
          echo "Checking connection to Splice services..."
          PGPASSWORD="$PERFORMANCE_TESTS_DB_PASSWORD" psql -h"$PERFORMANCE_TESTS_DB_HOST" -U"$PERFORMANCE_TESTS_DB_USER" -dcantonnet -c '\l' || (echo "Connection to DB failed" && exit 1)
