name: CI on PRs (Splice Contributors)
on: # TODO: replace with main only, once a day
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-perftest
  cancel-in-progress: true

permissions:
  id-token: write # Required for GCP Workload Identity for failure notifications
  contents: read

jobs:
  performance_tests:
    runs-on: self-hosted-k8s-small
    container:
      image: us-central1-docker.pkg.dev/da-cn-shared/ghcr/digital-asset/decentralized-canton-sync-dev/docker/splice-test-ci:0.3.12
    name: Performance Tests
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ''
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        id: setup
        uses: ./splice-shared-gha/.github/actions/tests/common_test_setup
        with:
          test_name: oss
          target: 'oss'

      - name: Env vars
        shell: bash
        run: |
          sleep 600
          echo "Checking connection to Splice services... Connecting to '$PERFORMANCE_TESTS_DB_HOST' with user '$PERFORMANCE_TESTS_DB_USER'..."

      - name: Connection check
        uses: ./splice-shared-gha/.github/actions/nix/run_bash_command_in_nix
        with:
          additional_nix_args: "--keep PERFORMANCE_TESTS_DB_PASSWORD --keep PERFORMANCE_TESTS_DB_HOST --keep PERFORMANCE_TESTS_DB_USER"
          cmd: ./scripts/check-cloudsql-conn.sh
