# Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

imageRepo: "ghcr.io/digital-asset/decentralized-canton-sync/docker"

# Custom annotations and labels for deployed resources
pod:
  annotations: {}
  labels: {}

defaultJvmOptions: -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=75 -Dscala.concurrent.context.numThreads=8 -XX:ActiveProcessorCount=8 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/persistent-data
resources:
  limits:
    cpu: "2"
    memory: 8Gi
  requests:
    cpu: "1"
    memory: 4Gi

mediator:
  persistence:
    host: postgres.sv-1.svc.cluster.local
    secretName: "postgres-secrets"

sequencer:
  persistence:
    host: postgres.sv-1.svc.cluster.local
    secretName: "postgres-secrets"

# k8s affinity for all deployed pods (optional)
# affinity:

# k8s nodeSelector for all deployed pods (optional)
# nodeSelector:

# k8s tolerations for all deployed pods (optional)
# tolerations:
